server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    charset utf-8;
    client_max_body_size 20M;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Laravel Routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Handle PHP
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    # Serve Livewire JS directly from published assets
    location = /livewire/livewire.js {
        expires 30d;
        alias /var/www/html/public/vendor/livewire/livewire.js;
    }
    location = /livewire/livewire.min.js {
        expires 30d;
        alias /var/www/html/public/vendor/livewire/livewire.min.js;
    }
    location = /livewire/livewire.min.js.map {
        alias /var/www/html/public/vendor/livewire/livewire.min.js.map;
    }

    # Hide dotfiles
    location ~ /\.(?!well-known) {
        deny all;
    }

    # Cache static assets
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri $uri/ /index.php?$query_string;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
